// Generated by CIRCT firtool-1.75.0
module IntSyncCrossingSource_n4x1_Registered(	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:48:9]
  input  auto_in_3_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  auto_in_2_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  auto_in_1_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  auto_in_0_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output auto_out_3_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output auto_out_2_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output auto_out_1_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output auto_out_0_sync_0	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  assign auto_out_3_sync_0 = auto_in_3_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:48:9]
  assign auto_out_2_sync_0 = auto_in_2_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:48:9]
  assign auto_out_1_sync_0 = auto_in_1_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:48:9]
  assign auto_out_0_sync_0 = auto_in_0_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:48:9]
endmodule

