// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLPLIC(	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
  input         auto_int_in_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_int_out_7_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_int_out_6_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_int_out_5_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_int_out_4_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_int_out_3_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_int_out_2_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_int_out_1_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_int_out_0_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [10:0] auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [27:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [10:0] auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_in_d_bits_data	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire        out_woready_16;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_woready_25;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_woready_2;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_woready_7;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_woready_13;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_woready_22;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_woready_8;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_woready_19;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_rofireMux_T_1;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_120;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_112;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_104;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_96;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_88;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_80;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_72;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_64;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        completer_6;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        completerDev;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
  wire        completer_2;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        completer_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        completer_7;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        completer_3;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        completer_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        completer_4;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        completer_5;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_back_front_q_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_back_front_q_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_back_front_q_io_deq_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [22:0] _out_back_front_q_io_deq_bits_index;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [63:0] _out_back_front_q_io_deq_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [7:0]  _out_back_front_q_io_deq_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [10:0] _out_back_front_q_io_deq_bits_extra_tlrr_extra_source;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_back_front_q_io_deq_bits_extra_tlrr_extra_size;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _fanin_7_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_7_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_6_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_6_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_5_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_5_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_4_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_4_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_3_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_3_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_2_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_2_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_1_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_1_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _fanin_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  wire        _gateways_gateway_io_plic_valid;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:158:27]
  reg         priority_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31]
  reg         threshold_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31]
  reg         threshold_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31]
  reg         threshold_2;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31]
  reg         threshold_3;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31]
  reg         threshold_4;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31]
  reg         threshold_5;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31]
  reg         threshold_6;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31]
  reg         threshold_7;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31]
  reg         pending_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26]
  reg         enables_0_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26]
  reg         enables_1_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26]
  reg         enables_2_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26]
  reg         enables_3_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26]
  reg         enables_4_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26]
  reg         enables_5_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26]
  reg         enables_6_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26]
  reg         enables_7_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26]
  reg         maxDevs_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22]
  reg         maxDevs_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22]
  reg         maxDevs_2;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22]
  reg         maxDevs_3;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22]
  reg         maxDevs_4;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22]
  reg         maxDevs_5;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22]
  reg         maxDevs_6;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22]
  reg         maxDevs_7;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22]
  reg         intnodeOut_0_REG;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:191:45]
  reg         intnodeOut_0_REG_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:191:45]
  reg         intnodeOut_0_REG_2;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:191:45]
  reg         intnodeOut_0_REG_3;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:191:45]
  reg         intnodeOut_0_REG_4;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:191:45]
  reg         intnodeOut_0_REG_5;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:191:45]
  reg         intnodeOut_0_REG_6;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:191:45]
  reg         intnodeOut_0_REG_7;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:191:45]
  wire [1:0]  _GEN = {1'h0, completerDev};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13, src/main/scala/chisel3/util/OneHot.scala:65:12]
  wire        _out_T_35 = {_out_back_front_q_io_deq_bits_index[22:19], _out_back_front_q_io_deq_bits_index[17:12], _out_back_front_q_io_deq_bits_index[8:7], _out_back_front_q_io_deq_bits_index[3:0]} == 16'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [31:0] _out_womask_T_25 = {{8{_out_back_front_q_io_deq_bits_mask[7]}}, {8{_out_back_front_q_io_deq_bits_mask[6]}}, {8{_out_back_front_q_io_deq_bits_mask[5]}}, {8{_out_back_front_q_io_deq_bits_mask[4]}}};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_5 = _out_rofireMux_T_1 & out_backSel_104 & _out_T_35 & (|_out_womask_T_25);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_completer_5_T = {enables_5_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :176:26, :181:52, :299:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_5 = out_woready_2 & (&_out_womask_T_25) & _out_completer_5_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_4 = _out_rofireMux_T_1 & out_backSel_96 & _out_T_35 & (|_out_womask_T_25);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_completer_4_T = {enables_4_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :176:26, :181:52, :299:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_4 = out_woready_7 & (&_out_womask_T_25) & _out_completer_4_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_1 = _out_rofireMux_T_1 & out_backSel_72 & _out_T_35 & (|_out_womask_T_25);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_completer_1_T = {enables_1_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :176:26, :181:52, :299:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_1 = out_woready_8 & (&_out_womask_T_25) & _out_completer_1_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_3 = _out_rofireMux_T_1 & out_backSel_88 & _out_T_35 & (|_out_womask_T_25);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_completer_3_T = {enables_3_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :176:26, :181:52, :299:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_3 = out_woready_13 & (&_out_womask_T_25) & _out_completer_3_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_7 = _out_rofireMux_T_1 & out_backSel_120 & _out_T_35 & (|_out_womask_T_25);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_completer_7_T = {enables_7_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :176:26, :181:52, :299:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_7 = out_woready_16 & (&_out_womask_T_25) & _out_completer_7_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_0 = _out_rofireMux_T_1 & out_backSel_64 & _out_T_35 & (|_out_womask_T_25);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_completer_0_T = {enables_0_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :176:26, :181:52, :299:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_0 = out_woready_19 & (&_out_womask_T_25) & _out_completer_0_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_2 = _out_rofireMux_T_1 & out_backSel_80 & _out_T_35 & (|_out_womask_T_25);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [1:0]  _out_completer_2_T = {enables_2_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :176:26, :181:52, :299:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_2 = out_woready_22 & (&_out_womask_T_25) & _out_completer_2_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_6 = _out_rofireMux_T_1 & out_backSel_112 & _out_T_35 & (|_out_womask_T_25);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign completerDev = _out_back_front_q_io_deq_bits_data[32];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
    wire [7:0] _GEN_0 = {claimer_7, claimer_6, claimer_5, claimer_4, claimer_3, claimer_2, claimer_1, claimer_0};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:21, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    wire [7:0] _GEN_1 = {completer_7, completer_6, completer_5, completer_4, completer_3, completer_2, completer_1, completer_0};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:266:23, :299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
      if (~reset & (|(_GEN_0 & _GEN_0 - 8'h1))) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:{11,21,28,46,54}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
          $error("Assertion failed\n    at Plic.scala:249 assert((claimer.asUInt & (claimer.asUInt - 1.U)) === 0.U) // One-Hot\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
      end
      if (~reset & (|(_GEN_1 & _GEN_1 - 8'h1))) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11, :266:{11,23,30,50,58}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:266:11]
          $error("Assertion failed\n    at Plic.scala:266 assert((completer.asUInt & (completer.asUInt - 1.U)) === 0.U) // One-Hot\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:266:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:266:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:266:11]
      end
      if (~reset & completerDev != _out_back_front_q_io_deq_bits_data[32]) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:{19,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:296 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
      end
      if (~reset & completerDev != _out_back_front_q_io_deq_bits_data[32]) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:{19,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:296 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
      end
      if (~reset & completerDev != _out_back_front_q_io_deq_bits_data[32]) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:{19,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:296 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
      end
      if (~reset & completerDev != _out_back_front_q_io_deq_bits_data[32]) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:{19,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:296 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
      end
      if (~reset & completerDev != _out_back_front_q_io_deq_bits_data[32]) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:{19,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:296 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
      end
      if (~reset & completerDev != _out_back_front_q_io_deq_bits_data[32]) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:{19,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:296 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
      end
      if (~reset & completerDev != _out_back_front_q_io_deq_bits_data[32]) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:{19,33}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $error("Assertion failed: completerDev should be consistent for all harts\n    at Plic.scala:296 assert(completerDev === data.extract(log2Ceil(nDevices+1)-1, 0),\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:296:19]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [1:0]  _out_completer_6_T = {enables_6_0, 1'h0} >> _GEN;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :176:26, :181:52, :299:51, src/main/scala/chisel3/util/OneHot.scala:65:12]
  assign completer_6 = out_woready_25 & (&_out_womask_T_25) & _out_completer_6_T[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:299:{35,51}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [6:0]  out_oindex = {_out_back_front_q_io_deq_bits_index[18], _out_back_front_q_io_deq_bits_index[11:9], _out_back_front_q_io_deq_bits_index[6:4]};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [6:0]  _GEN_2 = {_out_back_front_q_io_deq_bits_index[18], _out_back_front_q_io_deq_bits_index[11:9], _out_back_front_q_io_deq_bits_index[6:4]};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_64 = _GEN_2 == 7'h40;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_72 = _GEN_2 == 7'h48;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_80 = _GEN_2 == 7'h50;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_88 = _GEN_2 == 7'h58;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_96 = _GEN_2 == 7'h60;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_104 = _GEN_2 == 7'h68;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_112 = _GEN_2 == 7'h70;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_120 = _GEN_2 == 7'h78;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire        _out_wofireMux_T = _out_back_front_q_io_deq_valid & auto_in_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign _out_rofireMux_T_1 = _out_wofireMux_T & _out_back_front_q_io_deq_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_wofireMux_T_2 = _out_wofireMux_T & ~_out_back_front_q_io_deq_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_19 = _out_wofireMux_T_2 & out_backSel_64 & _out_T_35;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_8 = _out_wofireMux_T_2 & out_backSel_72 & _out_T_35;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_22 = _out_wofireMux_T_2 & out_backSel_80 & _out_T_35;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_13 = _out_wofireMux_T_2 & out_backSel_88 & _out_T_35;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_7 = _out_wofireMux_T_2 & out_backSel_96 & _out_T_35;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_2 = _out_wofireMux_T_2 & out_backSel_104 & _out_T_35;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_25 = _out_wofireMux_T_2 & out_backSel_112 & _out_T_35;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_woready_16 = _out_wofireMux_T_2 & out_backSel_120 & _out_T_35;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_out_bits_data_T_18 = out_oindex == 7'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:54:22]
  wire [2:0]  nodeIn_d_bits_opcode = {2'h0, _out_back_front_q_io_deq_bits_read};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, :105:19]
  wire        claiming = claimer_0 & maxDevs_0 | claimer_1 & maxDevs_1 | claimer_2 & maxDevs_2 | claimer_3 & maxDevs_3 | claimer_4 & maxDevs_4 | claimer_5 & maxDevs_5 | claimer_6 & maxDevs_6 | claimer_7 & maxDevs_7;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22, :250:{49,92}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    if (_out_wofireMux_T_2 & _GEN_2 == 7'h0 & _out_T_35 & _out_back_front_q_io_deq_bits_mask[4])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      priority_0 <= _out_back_front_q_io_deq_bits_data[32];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_19 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_0 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_8 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_1 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_22 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_2 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_13 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_3 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_7 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_4 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_2 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_5 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_25 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_6 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (out_woready_16 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      threshold_7 <= _out_back_front_q_io_deq_bits_data[0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:168:31, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 7'h10 & _out_T_35 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_0_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 7'h11 & _out_T_35 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_1_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 7'h12 & _out_T_35 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_2_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 7'h13 & _out_T_35 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_3_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 7'h14 & _out_T_35 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_4_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 7'h15 & _out_T_35 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_5_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 7'h16 & _out_T_35 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_6_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    if (_out_wofireMux_T_2 & _GEN_2 == 7'h17 & _out_T_35 & _out_back_front_q_io_deq_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      enables_7_0 <= _out_back_front_q_io_deq_bits_data[1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:176:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    maxDevs_0 <= _fanin_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22, :187:27]
    maxDevs_1 <= _fanin_1_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22, :187:27]
    maxDevs_2 <= _fanin_2_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22, :187:27]
    maxDevs_3 <= _fanin_3_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22, :187:27]
    maxDevs_4 <= _fanin_4_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22, :187:27]
    maxDevs_5 <= _fanin_5_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22, :187:27]
    maxDevs_6 <= _fanin_6_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22, :187:27]
    maxDevs_7 <= _fanin_7_io_dev;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:183:22, :187:27]
    intnodeOut_0_REG <= _fanin_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27, :191:45]
    intnodeOut_0_REG_1 <= _fanin_1_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27, :191:45]
    intnodeOut_0_REG_2 <= _fanin_2_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27, :191:45]
    intnodeOut_0_REG_3 <= _fanin_3_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27, :191:45]
    intnodeOut_0_REG_4 <= _fanin_4_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27, :191:45]
    intnodeOut_0_REG_5 <= _fanin_5_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27, :191:45]
    intnodeOut_0_REG_6 <= _fanin_6_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27, :191:45]
    intnodeOut_0_REG_7 <= _fanin_7_io_max;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27, :191:45]
    if (reset)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      pending_0 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :170:26]
    else if (claiming | _gateways_gateway_io_plic_valid)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:158:27, :250:92, :255:15]
      pending_0 <= ~claiming;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :250:92, :255:34]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
        end	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
        priority_0 = _RANDOM[1'h0][0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31]
        threshold_0 = _RANDOM[1'h0][1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :168:31]
        threshold_1 = _RANDOM[1'h0][2];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :168:31]
        threshold_2 = _RANDOM[1'h0][3];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :168:31]
        threshold_3 = _RANDOM[1'h0][4];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :168:31]
        threshold_4 = _RANDOM[1'h0][5];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :168:31]
        threshold_5 = _RANDOM[1'h0][6];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :168:31]
        threshold_6 = _RANDOM[1'h0][7];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :168:31]
        threshold_7 = _RANDOM[1'h0][8];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :168:31]
        pending_0 = _RANDOM[1'h0][9];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :170:26]
        enables_0_0 = _RANDOM[1'h0][10];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :176:26]
        enables_1_0 = _RANDOM[1'h0][11];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :176:26]
        enables_2_0 = _RANDOM[1'h0][12];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :176:26]
        enables_3_0 = _RANDOM[1'h0][13];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :176:26]
        enables_4_0 = _RANDOM[1'h0][14];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :176:26]
        enables_5_0 = _RANDOM[1'h0][15];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :176:26]
        enables_6_0 = _RANDOM[1'h0][16];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :176:26]
        enables_7_0 = _RANDOM[1'h0][17];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :176:26]
        maxDevs_0 = _RANDOM[1'h0][18];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :183:22]
        maxDevs_1 = _RANDOM[1'h0][19];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :183:22]
        maxDevs_2 = _RANDOM[1'h0][20];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :183:22]
        maxDevs_3 = _RANDOM[1'h0][21];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :183:22]
        maxDevs_4 = _RANDOM[1'h0][22];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :183:22]
        maxDevs_5 = _RANDOM[1'h0][23];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :183:22]
        maxDevs_6 = _RANDOM[1'h0][24];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :183:22]
        maxDevs_7 = _RANDOM[1'h0][25];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :183:22]
        intnodeOut_0_REG = _RANDOM[1'h0][26];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :191:45]
        intnodeOut_0_REG_1 = _RANDOM[1'h0][27];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :191:45]
        intnodeOut_0_REG_2 = _RANDOM[1'h0][28];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :191:45]
        intnodeOut_0_REG_3 = _RANDOM[1'h0][29];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :191:45]
        intnodeOut_0_REG_4 = _RANDOM[1'h0][30];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :191:45]
        intnodeOut_0_REG_5 = _RANDOM[1'h0][31];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :191:45]
        intnodeOut_0_REG_6 = _RANDOM[1'h1][0];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :191:45]
        intnodeOut_0_REG_7 = _RANDOM[1'h1][1];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :191:45]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_54 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_out_back_front_q_io_enq_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (_out_back_front_q_io_deq_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_in_d_bits_opcode  (nodeIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:105:19]
    .io_in_d_bits_size    (_out_back_front_q_io_deq_bits_extra_tlrr_extra_size),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_in_d_bits_source  (_out_back_front_q_io_deq_bits_extra_tlrr_extra_source)	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  LevelGateway gateways_gateway (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:158:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_0),
    .io_plic_valid    (_gateways_gateway_io_plic_valid),
    .io_plic_ready    (~pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :254:18]
    .io_plic_complete ((completer_0 | completer_1 | completer_2 | completer_3 | completer_4 | completer_5 | completer_6 | completer_7) & completerDev)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:268:{28,48}, :299:35, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/package.scala:163:13]
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:158:27]
  PLICFanIn fanin (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31]
    .io_ip     (enables_0_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :176:26, :189:40]
    .io_dev    (_fanin_io_dev),
    .io_max    (_fanin_io_max)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  PLICFanIn fanin_1 (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31]
    .io_ip     (enables_1_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :176:26, :189:40]
    .io_dev    (_fanin_1_io_dev),
    .io_max    (_fanin_1_io_max)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  PLICFanIn fanin_2 (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31]
    .io_ip     (enables_2_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :176:26, :189:40]
    .io_dev    (_fanin_2_io_dev),
    .io_max    (_fanin_2_io_max)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  PLICFanIn fanin_3 (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31]
    .io_ip     (enables_3_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :176:26, :189:40]
    .io_dev    (_fanin_3_io_dev),
    .io_max    (_fanin_3_io_max)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  PLICFanIn fanin_4 (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31]
    .io_ip     (enables_4_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :176:26, :189:40]
    .io_dev    (_fanin_4_io_dev),
    .io_max    (_fanin_4_io_max)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  PLICFanIn fanin_5 (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31]
    .io_ip     (enables_5_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :176:26, :189:40]
    .io_dev    (_fanin_5_io_dev),
    .io_max    (_fanin_5_io_max)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  PLICFanIn fanin_6 (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31]
    .io_ip     (enables_6_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :176:26, :189:40]
    .io_dev    (_fanin_6_io_dev),
    .io_max    (_fanin_6_io_max)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  PLICFanIn fanin_7 (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
    .io_prio_0 (priority_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:165:31]
    .io_ip     (enables_7_0 & pending_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:170:26, :176:26, :189:40]
    .io_dev    (_fanin_7_io_dev),
    .io_max    (_fanin_7_io_max)
  );	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:187:27]
  Queue1_RegMapperInput_i23_m8 out_back_front_q (	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .clock                               (clock),
    .reset                               (reset),
    .io_enq_ready                        (_out_back_front_q_io_enq_ready),
    .io_enq_valid                        (auto_in_a_valid),
    .io_enq_bits_read                    (auto_in_a_bits_opcode == 3'h4),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36]
    .io_enq_bits_index                   (auto_in_a_bits_address[25:3]),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19]
    .io_enq_bits_data                    (auto_in_a_bits_data),
    .io_enq_bits_mask                    (auto_in_a_bits_mask),
    .io_enq_bits_extra_tlrr_extra_source (auto_in_a_bits_source),
    .io_enq_bits_extra_tlrr_extra_size   (auto_in_a_bits_size),
    .io_deq_ready                        (auto_in_d_ready),
    .io_deq_valid                        (_out_back_front_q_io_deq_valid),
    .io_deq_bits_read                    (_out_back_front_q_io_deq_bits_read),
    .io_deq_bits_index                   (_out_back_front_q_io_deq_bits_index),
    .io_deq_bits_data                    (_out_back_front_q_io_deq_bits_data),
    .io_deq_bits_mask                    (_out_back_front_q_io_deq_bits_mask),
    .io_deq_bits_extra_tlrr_extra_source (_out_back_front_q_io_deq_bits_extra_tlrr_extra_source),
    .io_deq_bits_extra_tlrr_extra_size   (_out_back_front_q_io_deq_bits_extra_tlrr_extra_size)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_int_out_7_0 = intnodeOut_0_REG_7 > threshold_7;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :168:31, :191:{45,60}]
  assign auto_int_out_6_0 = intnodeOut_0_REG_6 > threshold_6;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :168:31, :191:{45,60}]
  assign auto_int_out_5_0 = intnodeOut_0_REG_5 > threshold_5;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :168:31, :191:{45,60}]
  assign auto_int_out_4_0 = intnodeOut_0_REG_4 > threshold_4;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :168:31, :191:{45,60}]
  assign auto_int_out_3_0 = intnodeOut_0_REG_3 > threshold_3;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :168:31, :191:{45,60}]
  assign auto_int_out_2_0 = intnodeOut_0_REG_2 > threshold_2;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :168:31, :191:{45,60}]
  assign auto_int_out_1_0 = intnodeOut_0_REG_1 > threshold_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :168:31, :191:{45,60}]
  assign auto_int_out_0_0 = intnodeOut_0_REG > threshold_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :168:31, :191:{45,60}]
  assign auto_in_a_ready = _out_back_front_q_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_valid = _out_back_front_q_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:105:19]
  assign auto_in_d_bits_size = _out_back_front_q_io_deq_bits_extra_tlrr_extra_size;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_bits_source = _out_back_front_q_io_deq_bits_extra_tlrr_extra_source;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_bits_data = ~(_out_out_bits_data_T_18 | out_oindex == 7'h8 | out_oindex == 7'h10 | out_oindex == 7'h11 | out_oindex == 7'h12 | out_oindex == 7'h13 | out_oindex == 7'h14 | out_oindex == 7'h15 | out_oindex == 7'h16 | out_oindex == 7'h17 | out_oindex == 7'h40 | out_oindex == 7'h48 | out_oindex == 7'h50 | out_oindex == 7'h58 | out_oindex == 7'h60 | out_oindex == 7'h68 | out_oindex == 7'h70 | out_oindex == 7'h78) | _out_T_35 ? (_out_out_bits_data_T_18 ? {31'h0, priority_0, 32'h0} : out_oindex == 7'h8 ? {62'h0, pending_0, 1'h0} : out_oindex == 7'h10 ? {62'h0, enables_0_0, 1'h0} : out_oindex == 7'h11 ? {62'h0, enables_1_0, 1'h0} : out_oindex == 7'h12 ? {62'h0, enables_2_0, 1'h0} : out_oindex == 7'h13 ? {62'h0, enables_3_0, 1'h0} : out_oindex == 7'h14 ? {62'h0, enables_4_0, 1'h0} : out_oindex == 7'h15 ? {62'h0, enables_5_0, 1'h0} : out_oindex == 7'h16 ? {62'h0, enables_6_0, 1'h0} : out_oindex == 7'h17 ? {62'h0, enables_7_0, 1'h0} : out_oindex == 7'h40 ? {31'h0, maxDevs_0, 31'h0, threshold_0} : out_oindex == 7'h48 ? {31'h0, maxDevs_1, 31'h0, threshold_1} : out_oindex == 7'h50 ? {31'h0, maxDevs_2, 31'h0, threshold_2} : out_oindex == 7'h58 ? {31'h0, maxDevs_3, 31'h0, threshold_3} : out_oindex == 7'h60 ? {31'h0, maxDevs_4, 31'h0, threshold_4} : out_oindex == 7'h68 ? {31'h0, maxDevs_5, 31'h0, threshold_5} : out_oindex == 7'h70 ? {31'h0, maxDevs_6, 31'h0, threshold_6} : out_oindex == 7'h78 ? {31'h0, maxDevs_7, 31'h0, threshold_7} : 64'h0) : 64'h0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, :165:31, :168:31, :170:26, :176:26, :183:22, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:52:28, :54:{22,28}]
endmodule

